# Generated by Django 5.2.7 on 2025-11-12 18:17

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('birth_date', models.DateField()),
                ('it_languages', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('ruby', 'ruby')], max_length=100)),
                ('languages', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Italian', 'Italian'), ('Russian', 'Russian')], max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('qualification', models.CharField(choices=[('junior', 'junior'), ('senior', 'senior'), ('middle', 'middle')], max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
