# Generated by Django 5.2.7 on 2025-10-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Укажите язык написания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(max_length=100, verbose_name='Укажите издательство'),
        ),
    ]
