# Generated by Django 5.2.7 on 2025-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reviews_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name_user',
            field=models.CharField(max_length=100),
        ),
    ]
