# Generated by Django 5.2.7 on 2025-11-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_alter_reviews_name_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Укажите адрес')),
                ('inn', models.CharField(max_length=100, verbose_name='Укажите ИНН')),
                ('payment', models.TextField(choices=[('Карта', 'Карта'), ('Наличные', 'Наличные'), ('QR-код', 'QR-код')], max_length=100, verbose_name='Укажите способ оплаты')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
            ],
        ),
    ]
